var courses = [
    {
      "id": "1",
      "uniId": "187A43",
      "name": "Explorative Design 1 & 2",
      "school": "Vienna University of Technology",
      "type": ["Project"],
      "language": "English",
      "degree": "MScEng in Interaction Design",
      "ects": "12",
      "tags": ["Games", "Design", "Prototyping", "Ideation", "Teamwork", "Film", "Presentation"],
      "description": "Seven game design challenges in which we in a short amount of time prototyped different games. For each challenge the group members were shuffled."
    },
    {
      "id": "2",
      "uniId": "187A27",
      "name": "Design Studies",
      "school": "Vienna University of Technology",
      "type": ["Project", "Lectures"],
      "language": "German",
      "degree": "MScEng in Interaction Design",
      "ects": "3",
      "tags": ["Design", "Research", "Teamwork"],
      "description": "Lectures on how design meta-research is performed using the FDS-framework. Then a group project in which we filmed some fellow design students during a design session, transcribed the film and analyzed the resulting text through the FDS-framework."
    },
    ,
    {
      "id": "3",
      "uniId": "187A83",
      "name": "Disruptive Technologies",
      "school": "Vienna University of Technology",
      "type": ["Project"],
      "language": "German",
      "degree": "MScEng in Interaction Design",
      "ects": "3",
      "tags": ["Design", "Programming", "IoT"],
      "description": "This year the theme was IoT. My colleague Marcel and I created a magic wand that lights a lamp when the wand is pointed towards it and the words \"Alohomora\" are spoken. We explored multiple concepts during design but this was what we could implement."
    },
    {
      "id": "4",
      "uniId": "184.680",
      "name": "Information Design",
      "school": "Vienna University of Technology",
      "type": ["Assignments", "Lectures"],
      "language": "English",
      "degree": "MScEng in Interaction Design",
      "ects": "4.5",
      "tags": ["Design", "Visual Design", "Information Architecture", "Form", "Color"],
      "description": "Lectures with three different lecturers: a Visual Designer, a User Experience Designer, and an Engineer. We made four assignments focusing on visual design."
    },
    {
      "id": "5",
      "uniId": "187A54",
      "name": "Evaluation of Visualisation",
      "school": "Vienna University of Technology",
      "type": ["Lectures", "Assignments"],
      "language": "German",
      "degree": "MScEng in Interaction Design",
      "ects": "3",
      "tags": ["Design", "Visualisation", "Evaluation"],
      "description": ""
    },
    {
      "id": "6",
      "uniId": "187A67",
      "name": "Beyond the Desktop",
      "school": "Vienna University of Technology",
      "type": ["Project"],
      "language": "English",
      "degree": "MScEng in Interaction Design",
      "ects": "6",
      "tags": ["Design", "User Research", "Ideation", "Prototyping", "IoT"],
      "description": ""
    },
    {
      "id": "7",
      "uniId": "187A25",
      "name": "Building Interaction",
      "school": "Vienna University of Technology",
      "type": ["Project"],
      "language": "English",
      "degree": "MScEng in Interaction Design",
      "ects": "6",
      "tags": ["Design", "Programming", "IoT", "Ideation", "Prototyping"],
      "description": ""
    },
    {
      "id": "8",
      "uniId": "360-173",
      "name": "Marketing Basics",
      "school": "Vienna University of Technology",
      "type": ["Lectures"],
      "language": "German",
      "degree": "MScEng in Interaction Design",
      "ects": "3",
      "tags": ["Marketing"],
      "description": ""
    },
    {
      "id": "9",
      "uniId": "106.200",
      "name": "Art and Computers",
      "school": "Vienna University of Technology",
      "type": ["Assignments"],
      "language": "German",
      "degree": "MScEng in Interaction Design",
      "ects": "3",
      "tags": ["Art"],
      "description": ""
    },
    {
      "id": "10",
      "uniId": "187A69",
      "name": "User Research Methods",
      "school": "Vienna University of Technology",
      "type": ["Project", "Lectures", "Assignments"],
      "language": "English",
      "degree": "MScEng in Interaction Design",
      "ects": "6",
      "tags": ["User Research", "Design", "Research"],
      "description": ""
    }
  ]
